- name: Docker and Compose Installation
  hosts: test_vagrant_vm
  roles:
    - role: docker
      when: "ansible_facts['os_family'] == 'Debian'"
      # tags: never
    
    - role: compose
      when: "ansible_facts['os_family'] == 'Debian'"
      # tags: never
